### ISSUE TITLE
PyQt5.QtWebKit not found

### ISSUE THREAD

**Issue by swannie2** [mbridak/augratin#12]
Hello - having the following issue trying to run on MacOS.  I think I have all the requirements filled:

MacBook-Pro-8 augratin % python3 augratin.py
Traceback (most recent call last):
  File "augratin.py", line 30, in <module>
    from PyQt5.QtWebKit import *
ModuleNotFoundError: No module named 'PyQt5.QtWebKit'
MacBook-Pro-8 augratin % pip3 list | grep PyQt5
PyQt5                 5.15.7
PyQt5-sip             12.11.0
MacBook-Pro-8 augratin %

**Comment by mbridak** [comment]
Sorry, PyQt5.QtWebKit may not exist for macos. I don't have a mac to test with. I didn't see it on pypi. I googled around and saw references on how to build qtwebkit on macos https://github.com/qtwebkit/qtwebkit/wiki/Building-QtWebKit-on-macOS but as far as I can tell this would just build the binary for the library and maybe not the python bindings to that library.

**Comment by swannie2** [comment]
No worries, I came across that as well, but I also came across a bunch of stuff that implied QtWebKit was deprecated in favor of a newer library called QtWebEngine or something similar.  I'll dig in a bit more and see if I can figure it out.  It might put my python skills to the test! :)

Edit: Here's the page I was referencing about it being deprecated: https://stackoverflow.com/questions/37876987/cannot-import-qtwebkitwidgets-in-pyqt5

**Comment by mbridak** [comment]
Ah thank you very much for the heads up. I'll take a look at it.

**Comment by swannie2** [comment]
Well ... that sent me down an Internet rabbit hole!

<closes 30 browser tabs>

I couldn't get QtWebKit libraries to install on MacOS.  I think this issue is very specific to the M1 Mac.  For what it's worth, I switched over to my windows machine and was able to get it installed there, but I did have to manually add the QtWebKit libraries via pip, no big deal.  However, from what I'm reading, I think QtWebKit is going away in general, so it may not be supported on newer version of Python/Qt Framework - but I didn't get that deep into it.

**Comment by mbridak** [comment]
I created another branch using Web Engine. Try that one and tell me if it works for you.

**Comment by mbridak** [comment]
Sorry, didn't mean to close this before I got word from you that it works now.
When I merged my PR it closed it automagically.

**Comment by swannie2** [comment]
Success! Seems to be working!

**Comment by mbridak** [comment]
Excellent, thanks again for bringing this to my attention.
